name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup libboost
      run: sudo apt update; sudo apt install libboost-dev libboost-all-dev
    - name: build
      run: mkdir build;cd build;cmake ..;make;
    - name: Run Test fifo speed test
      run: ./build/demo_multiple_fifo
    - name: Run Test fifo content verification
      run: ./build/demo_fifo_verification
    - name: Run Test demo event boundary finder
      run: ./build/demo_evtboundary
