name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: build
      run: mkdir build;cd build;cmake ..;make;
    - name: Run Test fifo data verification
      run: ./build/demo_fifo_verification
    - name: Run Test fifo speed test
      run: ./build/demo_multiple_fifo
    - name: Run Test event boundary finder
      run: ./build/demo_evtboundary
